export const BOOKS = [
  {
    name: 'A Promised Land',
    author: 'Barack Obama',
    genre: 'Politics',
    status: 'Reading',
    dateCompleted: '',
  },
  {
    name: 'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life',
    author: 'Mark Manson',
    genre: 'Self Help',
    status: 'Read',
    dateCompleted: '',
  },
  {
    name: 'Peril',
    author: 'Bob Woodward, Robert Costa',
    genre: 'Politics',
    status: 'Read',
    dateCompleted: '2022',
  },
  {
    name: '21 Lessons for the 21st Century',
    author: 'Yuval Noah Harari',
    genre: 'Sociology',
    status: 'Read',
    dateCompleted: '2022',
  },
  {
    name: 'The Anthropocene Reviewed',
    author: 'John Green',
    genre: 'Short Stories',
    status: 'Read',
    dateCompleted: '2022',
  },
  {
    name: 'Clean Code',
    author: 'Robert C. Martin',
    genre: 'Programming',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Rage',
    author: 'Bob Woodward',
    genre: 'Politics',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'On Having No Head',
    author: 'Douglas E. Harding',
    genre: 'Spirituality',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'The Lord of the Rings The Return of the King',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'The Lord of the Rings The Two Towers',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Lord of the Rings the Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: '12 Rules for Life: An Antidote to Chaos',
    author: 'Jordan B. Peterson',
    genre: 'Self Help',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    genre: 'History',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Propaganda',
    author: 'Edward L. Bernays',
    genre: 'Psychology',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Fear: Trump in the White House',
    author: 'Bob Woodward',
    genre: 'Politics',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Animal Farm',
    author: 'George Orwell',
    genre: 'Politics',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: '1984',
    author: 'George Orwell',
    genre: 'Politics',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'Manufacturing Consent',
    author: 'Edward S. Herman, Noam Chomsky',
    genre: 'Politics',
    status: 'Read',
    dateCompleted: '2021',
  },
  {
    name: 'The Power of Now',
    author: 'Eckhart Tolle',
    genre: 'Spirituality',
    status: 'Read',
    dateCompleted: '2021',
  },
]
